services:
  docpouch:
#    image: ghcr.io/bfh-jtf/doc-pouch:latest
    image: docpouch:latest
    volumes:
      - "./db:/app/db"
      - "./log:/app/log"
    env_file: ./.env
    networks:
      - server
    restart: unless-stopped
networks:
  server:
    external: true
