name: Docker Publish

on:
  release:
    types: [created]
  workflow_run:
    workflows: [Release]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        run: | 
          docker build -t my-image .
          docker push my-image