import * as crypto from "crypto";

/**
 * Backend-agnostic document store interface.
 *
 * Every collection in DocPouch (users, documents, structures, API keys,
 * OIDC models, ...) is accessed exclusively through this interface. Two
 * implementations exist:
 *
 *  - `NedbStore`  — file-based (default, zero-config)
 *  - `MongoStore` — MongoDB backend for production deployments
 *
 * The interface mirrors the small subset of NeDB/MongoDB semantics that
 * DocPouch actually uses. Implementations MUST:
 *
 *  - accept plain-equality query objects (no operators are used by DocPouch)
 *  - generate 16-char alphanumeric ids (`[A-Za-z0-9]{16}`) for inserted
 *    documents that lack an `_id`, so cross-document references and the
 *    export/import id remapping keep working across backends
 *  - implement `updateOne`/`update` with NeDB-compatible callback shapes
 *    (see the method docs for the exact quirks that are load-bearing)
 */

/** Options for {@link IDocStore.remove}. */
export interface IRemoveOptions {
    /** Remove all matching documents, not just the first one. */
    multi?: boolean;
}

/** Options for {@link IDocStore.update} and {@link IDocStore.updateOne}. */
export interface IUpdateOptions {
    multi?: boolean;
    upsert?: boolean;
    /**
     * NeDB extension: resolve the callback/rejection with the number of
     * affected documents. DocPouch relies on the numeric result, so both
     * implementations must always report it.
     */
    returnUpdatedDocs?: boolean;
}

export interface ICallback<T> {
    (err: Error | null, result: T): void;
}

export interface IDocStore {
    /** Human-readable collection name (used in logs). */
    readonly name: string;
    /** Human-readable collection description (used in logs). */
    readonly description: string;

    /**
     * Count documents matching the query.
     */
    count(query: object): Promise<number>;

    /**
     * Insert a single document. Generates a 16-char alphanumeric `_id`
     * when the document does not carry one. Resolves with the inserted
     * document (including `_id`).
     */
    add<T = any>(inputData: T): Promise<T>;

    /**
     * Insert an array of documents (or a single document). NeDB treats
     * `insert()` with an array as bulk-insert; MongoStore translates this
     * to `insertMany`. Resolves with nothing; callers re-query by id when
     * they need the inserted state.
     */
    insertMany(inputData: any[]): Promise<void>;

    /**
     * Find all documents matching the query. Resolves with an empty array
     * when nothing matches (never null).
     */
    query<T = any>(query: object): Promise<T[]>;

    /**
     * Find the first document matching the query. Resolves with `null`
     * when nothing matches.
     */
    findOne<T = any>(query: object): Promise<T | null>;

    /**
     * Remove documents matching the query. Resolves with the number of
     * removed documents.
     */
    remove(query: object, options?: IRemoveOptions): Promise<number>;

    /**
     * Update by `_id` with a plain (non-operator) replacement payload.
     * Resolves with the number of affected documents (0 or 1).
     *
     * Both implementations MUST reject when the payload contains keys
     * starting with `$` (the guard against Mongo operator injection in
     * document content) — {@link NedbStore.update} and {@link MongoStore.update}
     * share this behavior via `assertPlainPayload`.
     */
    update(documentID: string, updateInfo: object): Promise<number>;

    /**
     * Low-level NeDB-style update used by the OIDC adapter and the import
     * remapper. `updateInfo` may be an operator document (`{$set: ...}`) or,
     * for upserts, a plain replacement object.
     *
     * NeDB semantics that are load-bearing here:
     *  - `upsert: true` inserts the *update* document as-is when no match
     *    exists (an operator payload is NOT applied to a copy of the query).
     *    MongoStore replicates this instead of using `findOneAndUpdate`
     *    with upsert, because Mongo would insert the query's `_id` too.
     *  - with `multi: true`, all matching documents are updated.
     *  - `remove`-style `{}` options means single-document update.
     *
     * Callback variant for call sites that still use the NeDB callback
     * convention (`datastore.update(query, update, options, cb)`).
     */
    updateOne(query: object, updateInfo: object, options: IUpdateOptions, callback?: ICallback<number>): Promise<number>;

    /**
     * Low-level NeDB-style insert. Used by the OIDC adapter and the
     * password-reset token store, which insert records whose `_id` is
     * generated by the caller (e.g. `apikey_...`).
     * Callback variant for call sites that still use the NeDB callback
     * convention.
     */
    insert(inputData: any, callback?: ICallback<any>): Promise<any>;

    /**
     * Low-level NeDB-style find. Used by the OIDC adapter and the
     * password-reset token store, which rely on the callback convention.
     */
    find<T = any>(query: object, callback?: ICallback<T[]>): Promise<T[]>;

    /**
     * Low-level NeDB-style remove. Resolves/returns the number of removed
     * documents. Callback variant for call sites that still use the NeDB
     * callback convention.
     */
    removeOne(query: object, options: IRemoveOptions, callback?: ICallback<number>): Promise<number>;

    /**
     * Flush/stop background maintenance (NeDB autocompaction; no-op for
     * MongoDB). Called on server shutdown.
     */
    stop(): void;

    /**
     * Close the underlying connection/datastore. Idempotent.
     */
    close(): Promise<void>;
}

/**
 * Guard shared by all update paths: plain replacement payloads must not
 * contain keys that look like database update operators. DocPouch applies
 * `{$set: payload}` internally, so a `$`-prefixed key inside `payload`
 * would either corrupt the document or inject operators into MongoDB.
 */
export function assertPlainPayload(payload: Record<string, unknown>): void {
    for (const k of Object.keys(payload)) {
        if (k.startsWith("$")) {
            throw new Error("Update contains disallowed operator keys");
        }
    }
}

/**
 * Generate an id compatible with NeDB's auto-generated ids: 16 chars,
 * `[A-Za-z0-9]`. DocPouch treats any 16-char alphanumeric string in
 * document content as a potential cross-document reference
 * (`DOCPOUCH_ID_REGEX`), and import/export round-trips rely on this
 * format, so MongoDB-backed stores must not use native ObjectIds.
 */
export function generateDocPouchId(): string {
    let id = "";
    while (id.length < 16) {
        // base64 is ~75% alphanumeric; discard + and / characters like
        // NeDB's customUtils.uid does.
        const chunk = crypto.randomBytes(16)
            .toString("base64")
            .replace(/[+/]/g, "");
        id += chunk;
    }
    return id.slice(0, 16);
}